changelog:
  exclude:
    authors:
      - dependabot
      - dependabot[bot]
    labels:
      - ignore-for-release
  categories:
    - title: Breaking changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Accessibility
      labels:
        - accessibility
    - title: Documentation
      labels:
        - documentation
    - title: Other changes
      labels:
        - "*"
